Final
sneeu-leeu/Project_1 pull request #5
Opened 2020-08-17 19:41 UTC by sneeu-leeu

## Clone of a YouTube page

#### In This Project we :
* Learned and applied HTML and CSS for media embedding
* Got to know flexBox
* Applied semantic HTML

by cloning a YouTube page

2020-08-17 20:07 UTC, expjazz requested changes
## Status: Changes Required :recycle: 

You did a very good job here. The page looks almost like the original :ok_hand: 

However, there are still changes to be made in order to make this project looks even better. For more detail, check the inline comments below. I will make a summary here:

- [x] There are a few repeated selectors. Group them together

- [ ] I saw that you have multiple branches. For the next project, work from one feature branch so you have more commits.

#### As stated above, the project looks really good.

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-08-17 20:07 UTC, expjazz commented on index.html
> +                <i class="fab fa-youtube"></i>
- [x] This should be an image:

![image](https://user-images.githubusercontent.com/61479648/90438097-dd975a00-e0a9-11ea-8e35-692b1f9c3ca1.png)

- [x] The size could be smaller, so it matches the original:

| Yours | Original |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/61479648/90438256-0fa8bc00-e0aa-11ea-9f0a-de5e973a83d1.png)|![image](https://user-images.githubusercontent.com/61479648/90438287-1afbe780-e0aa-11ea-8f8d-42f8ce3b78b4.png) |

2020-08-17 20:07 UTC, expjazz commented on index.html
> +                            <small class="small">3.5M</small>
- [x] The design could look more like the original. Try to pay more attention to the font-sizes, font-colors, and spacings.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/90438537-7e861500-e0aa-11ea-977b-6fb18f460bc9.png) | ![image](https://user-images.githubusercontent.com/61479648/90438677-ba20df00-e0aa-11ea-8482-781751e543aa.png) |

2020-08-17 20:07 UTC, expjazz commented on index.html
> +                        <i class="title-icon fas fa-share">share</i>
- [ ] It needs to be a button:

![image](https://user-images.githubusercontent.com/61479648/90439011-3b787180-e0ab-11ea-936a-ec4157abc283.png)

2020-08-17 20:07 UTC, expjazz commented on stylesheet.css
> +    display: -webkit-flex;
Great job worrying about other browsers

2020-08-17 20:07 UTC, expjazz commented on stylesheet.css
> +
- [ ] You could group those two selectors together since they have the same property

2020-08-17 20:07 UTC, expjazz commented on stylesheet.css
> +}
- [ ] You can also group the share with the share-left

2020-08-19 16:45 UTC, kevcap requested changes
# [STATUS] CHANGES REQUIRED♻️

Hi team,  good job on making the previously required changes! 💪
You guys are almost there, but in order to accomplish as the actual page, you are required to do these changes listed below: ⬇

### I saw that you guys changed the image of the youtube logo and added a share button, however, you guys didn't implement the abruption of the css selectors, and that's why I can't approve this project. 

_Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, in order to get more knowledge and have a better project to add at your portfolio.

[REQUIRED CHANGES]
- [x] Remove all the unnecessary repeated CSS code ([Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)). Explanation: You guys have a lot of repeated code, and it's not a good practice, remember to always code DRY (Don't Repeat Yourself).

[OPTIONAL CHANGES]
- [x] Your code is throwing some errors and warnings at the [HTML5 Validator](https://validator.w3.org/nu/#textarear), please fix them.
![image](https://user-images.githubusercontent.com/56762529/90665146-09d5e680-e222-11ea-976f-41818e985f8b.png)

- [x] Make your whole layout more section more similar to the original one;
- [x] Put your `css` files in a css folder. (To make your repo more professional)
- [ ] Improve the layout to make it more similar to the original youtube page;
- [x] Improve the icons to make it more similar to the original youtube page;
- [ ] Add a favicon to make it more similar to the original youtube page;
- [ ] use `border-box` to add that bar on the top of the elements, instead of using `<hr>`
- [ ] Add the title of the video to the title of the page;
- [ ] Implement the comments section

**Please make the required changes and resubmit for a new code review once you are ready**💪
<img src="https://media1.giphy.com/media/UjCXeFnYcI2R2/giphy.gif?cid=ecf05e47f85sszmncvz9gstxysd956tlk5y2gojz9vumla10&amp;rid=giphy.gif">

## As always, I wish you all the very best and see you both at the top🚀

👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

  
<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-08-19 16:45 UTC, kevincappuccino commented on stylesheet.css
> +}
- [ ] Remove all the unnecessary repeated CSS code ([Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) Tip: Create one only class like this: .d-flex{ display: flex } and use that same class in your index.html when you need it.

2020-08-20 16:49 UTC, kevcap requested changes
# [STATUS] CHANGES REQUIRED♻️

Hi team,  good job on making the previously required changes! 💪
You guys are almost there, but in order to accomplish as the actual page, you are required to do these changes listed below: ⬇

_Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, in order to get more knowledge and have a better project to add at your portfolio.

[REQUIRED CHANGES]
- [x] You guys still have a lot of repeated CSS code (e.g. `display: flex` repeats 9x) Remove all the unnecessary repeated CSS code ([Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)). 
Explanation: There's a lot of repeated code, and it's not a good practice, remember to always code DRY (Don't Repeat Yourself).
You guys have classes that do the same thing, yet they're separated. E.g.:
![image](https://user-images.githubusercontent.com/56762529/90800896-a1ebd280-e2eb-11ea-8792-a95dcbc239a3.png)
![image](https://user-images.githubusercontent.com/56762529/90800946-b4660c00-e2eb-11ea-84da-7fc9ff500f4a.png)
Those two classes add a display as flex, yet, they're separated. Kindly fix that boys! 💪

Tip: For example: Create one only class like this: 
```
.d-flex{ 
   display: flex
}
``` 
and use that same class in your HTML files when you need it. 
Apply the same logic (e.g. creating a `.w-100 { width: 100%}` and so on) of the example to **ALL** your repeated css rules listed below:

![image](https://user-images.githubusercontent.com/56762529/90798278-1de41b80-e2e8-11ea-9900-ca6e2ac92bf7.png)


[OPTIONAL CHANGES]
- [x] Now your video size [1] and your description section links and share button [2] are both with layout broken, I encourage you to fix that
![image](https://user-images.githubusercontent.com/56762529/90799916-49680580-e2ea-11ea-894f-e75f33fc43b6.png)

- [ ] Your page has a horizontal bar, you guys can fix that
![image](https://user-images.githubusercontent.com/56762529/90800050-7a483a80-e2ea-11ea-88ff-d6d9a022048c.png)



- [x] Your code is still throwing some errors and warnings at the [HTML5 Validator](https://validator.w3.org/nu/#textarear), please fix them.
![image](https://user-images.githubusercontent.com/56762529/90665146-09d5e680-e222-11ea-976f-41818e985f8b.png)

- [ ] Improve the layout to make it more similar to the original youtube page;
- [ ] Add a favicon to make it more similar to the original youtube page;
- [ ] use `border-box` to add that bar on the top of the elements, instead of using `<hr>`
- [x] Add the title of the video to the title of the page;
- [ ] Implement the comments section

**Please make the required changes and resubmit for a new code review once you are ready**💪

## As always, I wish you all the very best and see you both at the top🚀

👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

  
<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-08-20 16:49 UTC, kevincappuccino commented on css/style.css
> +    display: flex;
- [ ] Remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/))

2020-08-20 16:49 UTC, kevincappuccino commented on css/style.css
> +    display: flex;
- [ ] Remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/))

2020-08-20 16:49 UTC, kevincappuccino commented on css/style.css
> +    display: flex;
- [ ] Remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/))

2020-08-20 16:49 UTC, kevincappuccino commented on css/style.css
> +    display: flex;
- [ ] Remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/))

2020-08-20 16:49 UTC, kevincappuccino commented on css/style.css
> +    display: flex;
- [ ] Remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/))

2020-08-20 16:49 UTC, kevincappuccino commented on css/style.css
> +    display: flex;
- [ ] Remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/))

2020-08-20 16:49 UTC, kevincappuccino commented on css/style.css
> +    display: flex;
- [ ] Remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/))

2020-08-20 16:49 UTC, kevincappuccino commented on css/style.css
> +    display: flex;
- [ ] Remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/))

2020-08-21 18:58 UTC, SafaErden approved these changes
### [STATUS] Approved 💪

<hr>
Hi TEAM, you did a great job and I can smell the great effort that you put for your very first collaborative project.😉

<hr>

- Since your project fulfills the requirements, I'm approving your project.

- But you have more ways to go and many things to learn. As a personal comment, I can say that you need to improve your UI abilities and I believe you will. 🌴 Try to make each project better than the previous one.

- Good luck with the next project.

<hr>

Don't forget to merge with the master branch

Happy coding 💻

**TSE:** Safa ERDEN

If you have any question, you can contact me on slack: @safaerden

2020-08-21 20:24 UTC, merged